# Generated by Django 2.2.3 on 2019-07-30 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='通道名字')),
                ('gateway_id', models.IntegerField(verbose_name='三方支付ID')),
                ('gateway_name', models.CharField(max_length=256, verbose_name='三方支付名称')),
                ('extra_info', models.CharField(max_length=2048, verbose_name='通道拓展参数，Json数据')),
                ('pay_type', models.CharField(max_length=256, verbose_name='支付类型')),
                ('status', models.IntegerField(verbose_name='通道状态')),
                ('pc', models.BooleanField(default=False)),
                ('created', models.IntegerField(verbose_name='创建时间')),
                ('updated', models.IntegerField(null=True, verbose_name='更新时间')),
                ('data', models.CharField(max_length=2048, null=True, verbose_name='拓展字段')),
            ],
        ),
        migrations.CreateModel(
            name='Gateway',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='支付方名字')),
                ('app_id', models.CharField(max_length=256, verbose_name='APP_ID')),
                ('app_key', models.CharField(max_length=256, verbose_name='APP_KEY')),
                ('pay_url', models.CharField(max_length=256, verbose_name='发起订单地址')),
                ('created', models.IntegerField(verbose_name='创建时间')),
                ('updated', models.IntegerField(null=True, verbose_name='更新时间')),
                ('data', models.CharField(max_length=2048, null=True, verbose_name='拓展字段')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(db_index=True, max_length=256, verbose_name='订单号')),
                ('games_order', models.CharField(max_length=256, null=True, verbose_name='游戏方订单号')),
                ('pay_order', models.CharField(max_length=256, null=True, verbose_name='支付方订单号')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='订单金额')),
                ('pay_amount', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='实际支付金额')),
                ('pay_time', models.IntegerField(verbose_name='支付时间')),
                ('succeeded', models.BooleanField(default=False, verbose_name='支付状态')),
                ('pay_type', models.CharField(max_length=128, verbose_name='支付方式')),
                ('channel_id', models.IntegerField(verbose_name='通道Id')),
                ('channel_name', models.CharField(max_length=256, verbose_name='通道名字')),
                ('username', models.CharField(max_length=256, verbose_name='用户名字')),
                ('client_ip', models.CharField(max_length=256, verbose_name='用户IP地址')),
                ('notify_url', models.CharField(max_length=256, verbose_name='回调地址')),
                ('created', models.IntegerField(verbose_name='创建时间')),
                ('updated', models.IntegerField(null=True, verbose_name='更新时间')),
                ('data', models.CharField(max_length=2048, null=True, verbose_name='拓展字段')),
            ],
        ),
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(db_index=True, max_length=256, verbose_name='订单号')),
                ('games_order', models.CharField(max_length=256, null=True, verbose_name='游戏方订单号')),
                ('pay_order', models.CharField(max_length=256, null=True, verbose_name='支付方订单号')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='订单金额')),
                ('pay_amount', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='实际支付金额')),
                ('pay_time', models.IntegerField(verbose_name='支付时间')),
                ('succeeded', models.BooleanField(default=False, verbose_name='支付状态')),
                ('pay_type', models.CharField(max_length=128, verbose_name='支付方式')),
                ('channel_id', models.IntegerField(verbose_name='通道Id')),
                ('channel_name', models.CharField(max_length=256, verbose_name='通道名字')),
                ('username', models.CharField(max_length=256, verbose_name='用户名字')),
                ('client_ip', models.CharField(max_length=256, verbose_name='用户IP地址')),
                ('notify_url', models.CharField(max_length=256, verbose_name='回调地址')),
                ('created', models.IntegerField(verbose_name='创建时间')),
                ('updated', models.IntegerField(null=True, verbose_name='更新时间')),
                ('data', models.CharField(max_length=2048, null=True, verbose_name='拓展字段')),
            ],
        ),
    ]
