# Generated by Django 2.2.3 on 2019-07-30 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0003_auto_20190730_0844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pay_amount',
            field=models.DecimalField(decimal_places=2, max_digits=18, null=True, verbose_name='实际支付金额'),
        ),
        migrations.AlterField(
            model_name='order',
            name='pay_time',
            field=models.IntegerField(null=True, verbose_name='支付时间'),
        ),
    ]
